services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_NAME: h3
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOSTNAME: db
      RAILS_LOG_TO_STDOUT: "true"
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: h3
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
