services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: h3
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
