version: 2.1
orbs:
  ruby-rails: sul-dlss/ruby-rails@4.2.3
workflows:
  build:
    jobs:
      - ruby-rails/lint:
          name: lint
          context: dlss
      - ruby-rails/lint-erb:
          context: dlss
      - ruby-rails/test-rails:
          name: test
          context: dlss
          install-chrome: true
          before-test:
            - run:
                name: Install javascript dependencies and build assets
                command: bin/rake css:build
