# frozen_string_literal: true

module ApplicationHelper
  def human_boolean(boolean)
    boolean ? 'Yes' : 'No'
  end

  # Form with an id and for which all input tags have the form attribute set.
  # This is useful for forms that are not directly inside the form tag or
  # for forms that are inside other forms. (When a form is inside another form,
  # the browser will not submit the inner form.)
  # Unfortunately, Rails doesn't provide a clean seam for adding the form attribute
  # to the autogenerated hidden fields so here we are.
  def ided_form_with(**args, &)
    form_id = args[:id]

    raise ArgumentError, 'You must provide an id' unless form_id

    # form_html is the opening form tag and autogenerated hidden fields
    form_html = form_with(**args, &)
    # Add form attribute to all input tags
    form_html.gsub('<input', "<input form=\"#{form_id}\"").html_safe # rubocop:disable Rails/OutputSafety
  end
end
